import type { Book } from "./types";
import { computeSortTitle } from "./sortTitle";

/**
 * DEVELOPMENT / DEMO CATALOG DATA — NOT confirmed SSJC inventory.
 *
 * This is Phase 2 fixture data for validating the Find experience before any real
 * database or import pipeline exists (Phases 4/6/7/10). A handful of records use real
 * bibliographic facts about well-known children's books (title/author/illustrator/
 * publisher/year) where that made searches like "books by Eric Carle" meaningful to
 * test — this does not imply the school owns these copies. Every other record is
 * invented, using clearly fixture-only publisher names (e.g. "Willow & Fern Books",
 * "Compass Point Readers") that do not correspond to real companies.
 *
 * Cover images are not real artwork — see src/components/find/BookCover.tsx for the
 * generated, typographic placeholder used instead. Physical categories are a
 * provisional development taxonomy, not the school's final shelving system — see
 * src/lib/catalog/categories.ts.
 *
 * This module is the seam Phase 5 replaces: everything downstream (search, ranking,
 * autocomplete, the Find UI) consumes `books` as a plain array and shouldn't need to
 * change shape when it becomes a real database query.
 */

type RawBook = Omit<Book, "sortTitle">;

const rawBooks: RawBook[] = [
  {
    id: "very-hungry-caterpillar",
    title: "The Very Hungry Caterpillar",
    authors: ["Eric Carle"],
    illustrators: ["Eric Carle"],
    publisher: "Philomel Books",
    languageCode: "en",
    description: "A small caterpillar eats his way through the days of the week before becoming a butterfly.",
    ageMinMonths: 24,
    ageMaxMonths: 60,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "animals-nature",
    tags: ["caterpillars", "insects", "life cycle", "counting", "food"],
    illustrationStyles: ["collage", "painted"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 5,
    cover: { variant: 0 },
    publicationYear: 1969,
  },
  {
    id: "brown-bear-brown-bear",
    title: "Brown Bear, Brown Bear, What Do You See?",
    authors: ["Bill Martin Jr."],
    illustrators: ["Eric Carle"],
    publisher: "Henry Holt and Co.",
    languageCode: "en",
    description: "A repeating, rhyming parade of animals, each one a different color, builds early reading confidence.",
    ageMinMonths: 12,
    ageMaxMonths: 36,
    fictionType: "fiction",
    format: "board_book",
    physicalCategory: "animals-nature",
    tags: ["colors", "animals", "repetition", "rhyme"],
    illustrationStyles: ["painted", "collage"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 3,
    cover: { variant: 1 },
    publicationYear: 1967,
  },
  {
    id: "grouchy-ladybug",
    title: "The Grouchy Ladybug",
    authors: ["Eric Carle"],
    illustrators: ["Eric Carle"],
    publisher: "HarperCollins",
    languageCode: "en",
    description: "A bad-tempered ladybug picks fights all day long until a whale teaches her a lesson about size.",
    ageMinMonths: 36,
    ageMaxMonths: 60,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "feelings-relationships",
    tags: ["insects", "feelings", "time", "size"],
    illustrationStyles: ["collage", "painted"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 6,
    cover: { variant: 2 },
    publicationYear: 1977,
  },
  {
    id: "the-gruffalo",
    title: "The Gruffalo",
    authors: ["Julia Donaldson"],
    illustrators: ["Axel Scheffler"],
    publisher: "Macmillan Children's Books",
    languageCode: "en",
    description: "A clever mouse invents a fearsome creature to scare off predators in the deep dark wood — until the creature actually appears.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "stories-imagination",
    tags: ["forest", "animals", "courage", "rhyme", "monsters"],
    illustrationStyles: ["watercolor", "ink"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 8,
    cover: { variant: 3 },
    publicationYear: 1999,
  },
  {
    id: "pippi-longstocking",
    title: "Pippi Longstocking",
    authors: ["Astrid Lindgren"],
    illustrators: ["Ingrid Vang Nyman"],
    publisher: "Rabén & Sjögren",
    languageCode: "sv",
    description: "An extraordinarily strong, independent girl lives alone with a horse and a monkey and answers to no one.",
    ageMinMonths: 60,
    ageMaxMonths: 108,
    fictionType: "fiction",
    format: "chapter_book",
    physicalCategory: "stories-imagination",
    tags: ["adventure", "independence", "humor", "friendship"],
    illustrationStyles: ["ink"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 14,
    cover: { variant: 4 },
    publicationYear: 1945,
  },
  {
    id: "alfie-atkins-wants-to-choose",
    title: "Alfie Atkins Wants to Choose",
    authors: ["Gunilla Bergström"],
    illustrators: ["Gunilla Bergström"],
    publisher: "Rabén & Sjögren",
    languageCode: "sv",
    description: "A small boy and his patient father work through a very ordinary morning of getting dressed and deciding things for himself.",
    ageMinMonths: 24,
    ageMaxMonths: 60,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "feelings-relationships",
    tags: ["family", "independence", "everyday life", "feelings"],
    illustrationStyles: ["ink", "watercolor"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 6,
    cover: { variant: 0 },
    publicationYear: 1972,
  },
  {
    id: "pettson-and-findus-rooster",
    title: "Pettson and Findus: Finding a Rooster",
    authors: ["Sven Nordqvist"],
    illustrators: ["Sven Nordqvist"],
    publisher: "Opal",
    languageCode: "sv",
    description: "An old farmer and his mischievous cat invent an elaborate contraption to solve a very small farmyard problem.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "everyday-life-play",
    tags: ["friendship", "farm", "humor", "invention"],
    illustrationStyles: ["painted", "ink"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 9,
    cover: { variant: 1 },
    publicationYear: 1984,
  },
  {
    id: "goodnight-moon",
    title: "Goodnight Moon",
    authors: ["Margaret Wise Brown"],
    illustrators: ["Clement Hurd"],
    publisher: "Harper & Brothers",
    languageCode: "en",
    description: "A quiet, ritual goodnight to every object in a small rabbit's room, one by one.",
    ageMinMonths: 6,
    ageMaxMonths: 36,
    fictionType: "fiction",
    format: "board_book",
    physicalCategory: "everyday-life-play",
    tags: ["bedtime", "routines", "calm"],
    illustrationStyles: ["painted"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 4,
    cover: { variant: 2 },
    publicationYear: 1947,
  },
  {
    id: "dont-let-pigeon-drive-bus",
    title: "Don't Let the Pigeon Drive the Bus!",
    authors: ["Mo Willems"],
    illustrators: ["Mo Willems"],
    publisher: "Hyperion Books for Children",
    languageCode: "en",
    description: "A bus driver leaves for a moment, and a persistent pigeon spends the rest of the book trying to talk the reader into letting him drive.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "stories-imagination",
    tags: ["humor", "persistence", "transportation"],
    illustrationStyles: ["digital_illustration", "ink"],
    visualRealism: "cartoon",
    readAloudMinutes: 4,
    cover: { variant: 3 },
    publicationYear: 2003,
  },
  {
    id: "should-i-share-my-ice-cream",
    title: "Should I Share My Ice Cream?",
    subtitle: "An Elephant and Piggie Book",
    authors: ["Mo Willems"],
    illustrators: ["Mo Willems"],
    publisher: "Hyperion Books for Children",
    languageCode: "en",
    description: "An elephant agonizes over whether to share his ice cream before it melts, in a back-and-forth easy-reader dialogue.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "early_reader",
    physicalCategory: "feelings-relationships",
    tags: ["sharing", "friendship", "humor", "decision-making"],
    illustrationStyles: ["digital_illustration", "ink"],
    visualRealism: "cartoon",
    readAloudMinutes: 5,
    cover: { variant: 4 },
    publicationYear: 2011,
  },
  {
    id: "spot-goes-to-the-farm",
    title: "Spot Goes to the Farm",
    authors: ["Eric Hill"],
    illustrators: ["Eric Hill"],
    publisher: "Puffin Books",
    languageCode: "en",
    description: "A lift-the-flap visit to a farm, where a small dog meets each animal in turn.",
    ageMinMonths: 12,
    ageMaxMonths: 36,
    fictionType: "fiction",
    format: "board_book",
    physicalCategory: "animals-nature",
    tags: ["farm animals", "lift-the-flap", "counting"],
    illustrationStyles: ["digital_illustration"],
    visualRealism: "cartoon",
    readAloudMinutes: 3,
    cover: { variant: 0 },
    publicationYear: 1987,
  },
  {
    id: "where-the-wild-things-are",
    title: "Where the Wild Things Are",
    authors: ["Maurice Sendak"],
    illustrators: ["Maurice Sendak"],
    publisher: "Harper & Row",
    languageCode: "en",
    description: "A boy sent to bed without supper sails to an island of monsters and becomes their king, for a while.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "stories-imagination",
    tags: ["imagination", "feelings", "adventure", "monsters"],
    illustrationStyles: ["ink", "painted"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 6,
    cover: { variant: 1 },
    publicationYear: 1963,
  },
  {
    id: "guess-how-much-i-love-you",
    title: "Guess How Much I Love You",
    authors: ["Sam McBratney"],
    illustrators: ["Anita Jeram"],
    publisher: "Walker Books",
    languageCode: "en",
    description: "Two hares try to out-do each other describing how much they love one another, right up to bedtime.",
    ageMinMonths: 12,
    ageMaxMonths: 48,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "feelings-relationships",
    tags: ["family", "love", "bedtime", "animals"],
    illustrationStyles: ["watercolor"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 5,
    cover: { variant: 2 },
    publicationYear: 1994,
  },
  {
    id: "the-rainbow-fish",
    title: "The Rainbow Fish",
    authors: ["Marcus Pfister"],
    illustrators: ["Marcus Pfister"],
    publisher: "NorthSouth Books",
    languageCode: "en",
    description: "The most beautiful fish in the ocean learns that giving away his shimmering scales brings him friends.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "feelings-relationships",
    tags: ["sharing", "friendship", "ocean", "kindness"],
    illustrationStyles: ["painted", "mixed_media"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 6,
    cover: { variant: 3 },
    publicationYear: 1992,
  },
  {
    id: "julias-house-for-lost-creatures",
    title: "Julia's House for Lost Creatures",
    authors: ["Ben Hatke"],
    illustrators: ["Ben Hatke"],
    publisher: "First Second",
    languageCode: "en",
    description: "A girl's new house floats in on the back of a giant turtle, and she soon fills its spare rooms with odd, lonely visitors.",
    ageMinMonths: 48,
    ageMaxMonths: 84,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "stories-imagination",
    tags: ["friendship", "home", "community", "monsters"],
    illustrationStyles: ["watercolor", "ink"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 9,
    cover: { variant: 4 },
    publicationYear: 2014,
  },
  {
    id: "the-snowy-day",
    title: "The Snowy Day",
    authors: ["Ezra Jack Keats"],
    illustrators: ["Ezra Jack Keats"],
    publisher: "Viking Press",
    languageCode: "en",
    description: "A boy spends a whole day exploring his city block after the season's first snowfall.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "stories-imagination",
    tags: ["winter", "seasons", "imagination", "city life"],
    illustrationStyles: ["collage", "painted"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 5,
    cover: { variant: 0 },
    publicationYear: 1962,
  },
  {
    id: "winters-quiet-sleep",
    title: "Winter's Quiet Sleep",
    authors: ["Elin Berg"],
    illustrators: ["Elin Berg"],
    publisher: "Willow & Fern Books",
    languageCode: "en",
    description: "A gentle look at how squirrels, bears, and frogs each get ready for winter in their own way.",
    ageMinMonths: 48,
    ageMaxMonths: 84,
    fictionType: "nonfiction",
    format: "picture_book",
    physicalCategory: "animals-nature",
    tags: ["winter", "seasons", "hibernation", "animals"],
    illustrationStyles: ["watercolor"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 7,
    cover: { variant: 1 },
  },
  {
    id: "amazing-animal-babies",
    title: "Amazing Animal Babies",
    authors: ["Nora Ellis"],
    publisher: "Bright Meadow Press",
    languageCode: "en",
    description: "Real photographs introduce newborn animals from around the world and how their parents care for them.",
    ageMinMonths: 36,
    ageMaxMonths: 84,
    fictionType: "nonfiction",
    format: "informational_reference",
    physicalCategory: "animals-nature",
    tags: ["animals", "baby animals", "nature"],
    illustrationStyles: ["photography"],
    visualRealism: "real_photography",
    readAloudMinutes: 4,
    cover: { variant: 2 },
  },
  {
    id: "ocean-wonders",
    title: "Ocean Wonders",
    subtitle: "A Photographic Journey",
    authors: ["Marcus Webb"],
    publisher: "Bright Meadow Press",
    languageCode: "en",
    description: "Real underwater photography introduces coral reefs and the animals that live in them.",
    ageMinMonths: 48,
    ageMaxMonths: 96,
    fictionType: "nonfiction",
    format: "informational_reference",
    physicalCategory: "animals-nature",
    tags: ["ocean", "animals", "nature"],
    illustrationStyles: ["photography"],
    visualRealism: "real_photography",
    readAloudMinutes: 8,
    cover: { variant: 3 },
  },
  {
    id: "bugs-up-close",
    title: "Bugs Up Close",
    authors: ["Priya Anand"],
    publisher: "Compass Point Readers",
    languageCode: "en",
    description: "Close-up real photographs reveal the tiny details of beetles, ants, and butterflies.",
    ageMinMonths: 48,
    ageMaxMonths: 96,
    fictionType: "nonfiction",
    format: "informational_reference",
    physicalCategory: "animals-nature",
    tags: ["insects", "bugs", "nature", "life cycle"],
    illustrationStyles: ["photography"],
    visualRealism: "real_photography",
    readAloudMinutes: 5,
    cover: { variant: 4 },
  },
  {
    id: "dinosaur-bones",
    title: "Dinosaur Bones",
    authors: ["Tom Reyes"],
    publisher: "Compass Point Readers",
    languageCode: "en",
    description: "How paleontologists dig up, clean, and rebuild dinosaur skeletons for museums.",
    ageMinMonths: 60,
    ageMaxMonths: 108,
    fictionType: "nonfiction",
    format: "informational_reference",
    physicalCategory: "stem-discovery",
    tags: ["dinosaurs", "fossils", "science", "history"],
    illustrationStyles: ["photography", "digital_illustration"],
    visualRealism: "mixed",
    readAloudMinutes: 9,
    cover: { variant: 0 },
  },
  {
    id: "dinosaur-adventure",
    title: "Dinosaur Adventure",
    authors: ["Lena Ford"],
    illustrators: ["Lena Ford"],
    publisher: "Willow & Fern Books",
    languageCode: "en",
    description: "A child imagines a whole afternoon exploring a prehistoric jungle full of friendly dinosaurs.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "stories-imagination",
    tags: ["dinosaurs", "adventure", "imagination"],
    illustrationStyles: ["digital_illustration"],
    visualRealism: "cartoon",
    readAloudMinutes: 5,
    cover: { variant: 1 },
  },
  {
    id: "the-littlest-dinosaur",
    title: "The Littlest Dinosaur",
    authors: ["Anna Kask"],
    illustrators: ["Anna Kask"],
    publisher: "Willow & Fern Books",
    languageCode: "en",
    description: "The smallest dinosaur in the herd finds a clever way to keep up with everyone else.",
    ageMinMonths: 18,
    ageMaxMonths: 42,
    fictionType: "fiction",
    format: "board_book",
    physicalCategory: "stories-imagination",
    tags: ["dinosaurs", "size", "counting"],
    illustrationStyles: ["digital_illustration"],
    visualRealism: "cartoon",
    readAloudMinutes: 3,
    cover: { variant: 2 },
  },
  {
    id: "my-first-book-of-shapes",
    title: "My First Book of Shapes",
    authors: ["Clara Byrne"],
    publisher: "Compass Point Readers",
    languageCode: "en",
    description: "Circles, squares, and triangles hide in everyday objects on every page.",
    ageMinMonths: 6,
    ageMaxMonths: 30,
    fictionType: "nonfiction",
    format: "board_book",
    physicalCategory: "stem-discovery",
    tags: ["shapes", "colors", "counting", "early learning"],
    illustrationStyles: ["graphic_vector"],
    visualRealism: "abstract",
    readAloudMinutes: 2,
    cover: { variant: 3 },
  },
  {
    id: "numbers-on-our-street",
    title: "Numbers on Our Street",
    authors: ["Dev Patel"],
    illustrators: ["Dev Patel"],
    publisher: "Compass Point Readers",
    languageCode: "en",
    description: "Counting from one to ten using the ordinary sights of one busy neighborhood block.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "nonfiction",
    format: "picture_book",
    physicalCategory: "stem-discovery",
    tags: ["counting", "numbers", "community", "city life"],
    illustrationStyles: ["digital_illustration"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 5,
    cover: { variant: 4 },
  },
  {
    id: "how-plants-grow",
    title: "How Plants Grow",
    authors: ["Mei Lin"],
    publisher: "Bright Meadow Press",
    languageCode: "en",
    description: "From seed to sprout to flower, told through real photographs and simple watercolor diagrams.",
    ageMinMonths: 48,
    ageMaxMonths: 96,
    fictionType: "nonfiction",
    format: "informational_reference",
    physicalCategory: "stem-discovery",
    tags: ["plants", "gardening", "life cycle", "nature"],
    illustrationStyles: ["watercolor", "photography"],
    visualRealism: "mixed",
    readAloudMinutes: 7,
    cover: { variant: 0 },
  },
  {
    id: "machines-that-help-us",
    title: "Machines That Help Us",
    authors: ["Owen Brandt"],
    illustrators: ["Owen Brandt"],
    publisher: "Compass Point Readers",
    languageCode: "en",
    description: "Cranes, tractors, and street sweepers, and the jobs each one is built to do.",
    ageMinMonths: 48,
    ageMaxMonths: 96,
    fictionType: "nonfiction",
    format: "informational_reference",
    physicalCategory: "stem-discovery",
    tags: ["transportation", "community helpers", "machines"],
    illustrationStyles: ["digital_illustration"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 6,
    cover: { variant: 1 },
  },
  {
    id: "global-families",
    title: "Global Families",
    authors: ["Farah Nasser"],
    illustrators: ["Farah Nasser"],
    publisher: "Willow & Fern Books",
    languageCode: "en",
    description: "A gentle tour of mornings, meals, and homes in families from many different countries.",
    ageMinMonths: 48,
    ageMaxMonths: 96,
    fictionType: "nonfiction",
    format: "picture_book",
    physicalCategory: "world-cultures",
    tags: ["family", "diversity", "community", "traditions"],
    illustrationStyles: ["watercolor"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 6,
    cover: { variant: 2 },
  },
  {
    id: "celebrating-together",
    title: "Celebrating Together",
    authors: ["Farah Nasser"],
    illustrators: ["Farah Nasser"],
    publisher: "Willow & Fern Books",
    languageCode: "en",
    description: "A single street celebrates several different holidays across one school year.",
    ageMinMonths: 48,
    ageMaxMonths: 96,
    fictionType: "nonfiction",
    format: "picture_book",
    physicalCategory: "world-cultures",
    tags: ["traditions", "holidays", "community", "diversity"],
    illustrationStyles: ["collage"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 6,
    cover: { variant: 3 },
  },
  {
    id: "un-dia-en-el-mercado",
    title: "Un Día en el Mercado",
    subtitle: "A Day at the Market",
    authors: ["Rosa Delgado"],
    illustrators: ["Rosa Delgado"],
    publisher: "Luna Nueva Editorial",
    languageCode: "es",
    description: "A grandmother and granddaughter shop for the week's fruit and fish, greeting old friends at every stall.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "world-cultures",
    tags: ["community", "food", "family", "everyday life"],
    illustrationStyles: ["watercolor"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 6,
    cover: { variant: 4 },
  },
  {
    id: "mi-familia-y-yo",
    title: "Mi Familia y Yo",
    subtitle: "My Family and Me",
    authors: ["Rosa Delgado"],
    illustrators: ["Rosa Delgado"],
    publisher: "Luna Nueva Editorial",
    languageCode: "es",
    description: "A toddler introduces every member of a warm, noisy, multigenerational household.",
    ageMinMonths: 12,
    ageMaxMonths: 36,
    fictionType: "fiction",
    format: "board_book",
    physicalCategory: "people-community",
    tags: ["family", "love", "everyday life"],
    illustrationStyles: ["painted"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 3,
    cover: { variant: 0 },
  },
  {
    id: "elmer",
    title: "Elmer the Patchwork Elephant",
    authors: ["David McKee"],
    illustrators: ["David McKee"],
    publisher: "Andersen Press",
    languageCode: "en",
    description: "A brightly patchworked elephant tries to fit in by turning grey like the rest of the herd, for one day.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "feelings-relationships",
    tags: ["identity", "friendship", "diversity", "colors"],
    illustrationStyles: ["graphic_vector", "painted"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 5,
    cover: { variant: 1 },
    publicationYear: 1968,
  },
  {
    id: "froet-som-ville-blomstre",
    title: "Frøet som ville blomstre",
    subtitle: "The Seed That Wanted to Bloom",
    authors: ["Kari Solberg"],
    illustrators: ["Kari Solberg"],
    publisher: "Nordlys Forlag",
    languageCode: "no",
    description: "An impatient little seed learns that becoming a flower cannot be rushed.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "animals-nature",
    tags: ["plants", "patience", "life cycle", "gardening"],
    illustrationStyles: ["watercolor"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 5,
    cover: { variant: 2 },
  },
  {
    id: "bestefars-bat",
    title: "Bestefars Båt",
    subtitle: "Grandpa's Boat",
    authors: ["Kari Solberg"],
    illustrators: ["Kari Solberg"],
    publisher: "Nordlys Forlag",
    languageCode: "no",
    description: "A grandfather teaches his grandchild to read the wind and the water on their first fishing trip together.",
    ageMinMonths: 48,
    ageMaxMonths: 84,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "people-community",
    tags: ["family", "adventure", "sea", "intergenerational"],
    illustrationStyles: ["painted"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 7,
    cover: { variant: 3 },
  },
  {
    id: "den-lille-froe",
    title: "Den Lille Frø",
    subtitle: "The Little Frog",
    authors: ["Mette Holm"],
    illustrators: ["Mette Holm"],
    publisher: "Nordisk Bogforlag",
    languageCode: "da",
    description: "A tiny frog explores every corner of its pond for the very first time.",
    ageMinMonths: 12,
    ageMaxMonths: 36,
    fictionType: "fiction",
    format: "board_book",
    physicalCategory: "animals-nature",
    tags: ["animals", "ponds", "colors"],
    illustrationStyles: ["digital_illustration"],
    visualRealism: "cartoon",
    readAloudMinutes: 2,
    cover: { variant: 4 },
  },
  {
    id: "skoven-om-natten",
    title: "Skoven om Natten",
    subtitle: "The Forest at Night",
    authors: ["Mette Holm"],
    illustrators: ["Mette Holm"],
    publisher: "Nordisk Bogforlag",
    languageCode: "da",
    description: "A fox cub finds the forest a little less frightening once its night-time sounds have names.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "animals-nature",
    tags: ["forest", "nighttime", "animals", "courage"],
    illustrationStyles: ["ink", "watercolor"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 6,
    cover: { variant: 0 },
  },
  {
    id: "larbre-magique",
    title: "L'Arbre Magique",
    subtitle: "The Magic Tree",
    authors: ["Camille Roy"],
    illustrators: ["Camille Roy"],
    publisher: "Petite Lumière Éditions",
    languageCode: "fr",
    description: "A tree in the schoolyard grows a different, impossible fruit with each season.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "stories-imagination",
    tags: ["imagination", "trees", "magic", "seasons"],
    illustrationStyles: ["watercolor"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 5,
    cover: { variant: 1 },
  },
  {
    id: "the-napping-house",
    title: "The Napping House",
    authors: ["Audrey Wood"],
    illustrators: ["Don Wood"],
    publisher: "Harcourt",
    languageCode: "en",
    description: "A granny, a child, a dog, a cat, and a mouse pile onto one bed until a single flea changes everything.",
    ageMinMonths: 24,
    ageMaxMonths: 60,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "everyday-life-play",
    tags: ["bedtime", "humor", "repetition", "family"],
    illustrationStyles: ["painted"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 4,
    cover: { variant: 2 },
    publicationYear: 1984,
  },
  {
    id: "blueberries-for-sal",
    title: "Blueberries for Sal",
    authors: ["Robert McCloskey"],
    illustrators: ["Robert McCloskey"],
    publisher: "Viking Press",
    languageCode: "en",
    description: "A girl and a bear cub each lose track of their mothers on the very same blueberry hill.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "animals-nature",
    tags: ["family", "nature", "animals", "seasons"],
    illustrationStyles: ["pencil"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 6,
    cover: { variant: 3 },
    publicationYear: 1948,
  },
  {
    id: "corduroy",
    title: "Corduroy",
    authors: ["Don Freeman"],
    illustrators: ["Don Freeman"],
    publisher: "Viking Press",
    languageCode: "en",
    description: "A department-store bear missing a button spends one night searching the store for it.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "feelings-relationships",
    tags: ["friendship", "toys", "city life", "patience"],
    illustrationStyles: ["painted"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 6,
    cover: { variant: 4 },
    publicationYear: 1968,
  },
  {
    id: "harold-and-the-purple-crayon",
    title: "Harold and the Purple Crayon",
    authors: ["Crockett Johnson"],
    illustrators: ["Crockett Johnson"],
    publisher: "Harper & Brothers",
    languageCode: "en",
    description: "A boy draws an entire moonlit adventure into existence with a single purple crayon.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "arts-creativity",
    tags: ["imagination", "drawing", "adventure"],
    illustrationStyles: ["ink"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 4,
    cover: { variant: 0 },
    publicationYear: 1955,
  },
  {
    id: "ish",
    title: "Ish",
    authors: ["Peter H. Reynolds"],
    illustrators: ["Peter H. Reynolds"],
    publisher: "Candlewick Press",
    languageCode: "en",
    description: "A boy stops drawing altogether until his sister shows him his pictures were never about being perfect.",
    ageMinMonths: 48,
    ageMaxMonths: 84,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "arts-creativity",
    tags: ["art", "creativity", "confidence", "imagination"],
    illustrationStyles: ["watercolor", "ink"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 5,
    cover: { variant: 1 },
    publicationYear: 2004,
  },
  {
    id: "the-dot",
    title: "The Dot",
    authors: ["Peter H. Reynolds"],
    illustrators: ["Peter H. Reynolds"],
    publisher: "Candlewick Press",
    languageCode: "en",
    description: "A teacher convinces a frustrated student that a single dot on a page is worth signing her name to.",
    ageMinMonths: 48,
    ageMaxMonths: 84,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "arts-creativity",
    tags: ["art", "creativity", "confidence"],
    illustrationStyles: ["watercolor", "ink"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 4,
    cover: { variant: 2 },
    publicationYear: 2003,
  },
  {
    id: "music-and-movement",
    title: "A Little Bit of Music and Movement",
    authors: ["Jonas Ahl"],
    illustrators: ["Jonas Ahl"],
    publisher: "Compass Point Readers",
    languageCode: "en",
    description: "Simple rhythms and motions to try together, from tiptoeing to stomping.",
    ageMinMonths: 24,
    ageMaxMonths: 60,
    fictionType: "nonfiction",
    format: "picture_book",
    physicalCategory: "everyday-life-play",
    tags: ["music", "movement", "rhythm", "everyday life"],
    illustrationStyles: ["digital_illustration"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 4,
    cover: { variant: 3 },
  },
  {
    id: "kitchen-helpers",
    title: "Kitchen Helpers",
    subtitle: "Simple Recipes for Little Hands",
    authors: ["Ines Moller"],
    publisher: "Bright Meadow Press",
    languageCode: "en",
    description: "Real step-by-step photographs walk young cooks through three no-stove recipes.",
    ageMinMonths: 48,
    ageMaxMonths: 96,
    fictionType: "nonfiction",
    format: "informational_reference",
    physicalCategory: "everyday-life-play",
    tags: ["cooking", "family", "counting", "everyday life"],
    illustrationStyles: ["photography"],
    visualRealism: "real_photography",
    readAloudMinutes: 8,
    cover: { variant: 4 },
  },
  {
    id: "community-helpers-on-our-street",
    title: "Community Helpers on Our Street",
    authors: ["Owen Brandt"],
    publisher: "Compass Point Readers",
    languageCode: "en",
    description: "Real photographs introduce the mail carrier, the firefighter, and the crossing guard by name.",
    ageMinMonths: 48,
    ageMaxMonths: 96,
    fictionType: "nonfiction",
    format: "informational_reference",
    physicalCategory: "people-community",
    tags: ["community helpers", "city life", "transportation"],
    illustrationStyles: ["photography"],
    visualRealism: "real_photography",
    readAloudMinutes: 7,
    cover: { variant: 0 },
  },
  {
    id: "big-feelings-small-moments",
    title: "Big Feelings, Small Moments",
    authors: ["Dana Cole"],
    illustrators: ["Dana Cole"],
    publisher: "Willow & Fern Books",
    languageCode: "en",
    description: "A calm, page-by-page way to notice and name a feeling before it gets too big.",
    ageMinMonths: 36,
    ageMaxMonths: 72,
    fictionType: "fiction",
    format: "picture_book",
    physicalCategory: "feelings-relationships",
    tags: ["feelings", "calm", "mindfulness", "friendship"],
    illustrationStyles: ["watercolor"],
    visualRealism: "stylized_illustration",
    readAloudMinutes: 5,
    cover: { variant: 1 },
  },
  {
    id: "friends-through-thick-and-thin",
    title: "Friends Through Thick and Thin",
    authors: ["Dana Cole"],
    illustrators: ["Dana Cole"],
    publisher: "Willow & Fern Books",
    languageCode: "en",
    description: "Two classmates argue, apologize, and figure out how to stay friends through a whole school year.",
    ageMinMonths: 84,
    ageMaxMonths: 132,
    fictionType: "fiction",
    format: "chapter_book",
    physicalCategory: "feelings-relationships",
    tags: ["friendship", "courage", "growing up"],
    illustrationStyles: ["pencil"],
    visualRealism: "realistic_illustration",
    readAloudMinutes: 12,
    cover: { variant: 2 },
  },
];

export const books: Book[] = rawBooks.map((book) => ({
  ...book,
  sortTitle: computeSortTitle(book.title),
}));

export function getBookById(id: string): Book | undefined {
  return books.find((book) => book.id === id);
}
